package org.sonar.go.plugin;

import org.sonar.api.Plugin;
import org.sonar.api.config.PropertyDefinition;
import org.sonar.api.resources.Qualifiers;

public class GoPlugin implements Plugin {

  static final String RESOURCE_FOLDER = "org/sonar/l10n/go/rules/go";

  private static final String GO_CATEGORY = "Go";

  @Override
  public void define(Context context) {
    context.addExtensions(
      GoLanguage.class,
      GoSensor.class,
      GoRulesDefinition.class,
      SonarWayProfile.class,
      PropertyDefinition.builder(GoCoverageReport.REPORT_PATH_KEY)
        .name("Path to coverage report(s)")
        .description("Path to coverage reports generated by Go (e.g.: go test -coverprofile=coverage.out).")
        .category(GO_CATEGORY)
        .onQualifiers(Qualifiers.PROJECT)
        .defaultValue(GoCoverageReport.DEFAULT_REPORT_PATH)
        .multiValues(true)
        .build()
      );
  }
}
